vich_uploader:
    db_driver: orm


    mappings:
        jeux_image:
            uri_prefix: /Uploads/Images
            upload_destination: '%kernel.project_dir%/public/Uploads/Images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        competition_image:
            uri_prefix: /Uploads/Images
            upload_destination: '%kernel.project_dir%/public/Uploads/Images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer