<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWnBd9RS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWnBd9RS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWnBd9RS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWnBd9RS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWnBd9RS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WnBd9RS',
    'container.build_id' => '15d93921',
    'container.build_time' => 1646740090,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWnBd9RS');
